services:
  db:
    image: postgres:16
    container_name: drones-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: drones_api
      POSTGRES_USER: drones
      POSTGRES_PASSWORD: drones_password
    ports:
      - "5432:5432"
    volumes:
      - drones_api_pgdata:/var/lib/postgresql/data

volumes:
  drones_api_pgdata:
